NAME=domain-policy
DESCRIPTION="ALT Domain Policy"

INSTALL=/usr/bin/install

all: 
clean: 
install: install-module install-data

include /usr/share/alterator/build/module.mak

install-data:
	install -d $(sysconfdir)/alterator
